<a href="https://colab.research.google.com/github/WilliamPoe/CSCI-290/blob/main/notebooks/Gaussian_Mixtures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from sklearn.mixture import GaussianMixture
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df_penguin = pd.read_csv('https://github.com/WilliamPoe/CSCI-290/raw/refs/heads/main/Data/penguins.csv') # Penguins dataset
df_iris = pd.read_csv('https://github.com/WilliamPoe/CSCI-290/raw/refs/heads/main/Data/Iris.csv') # Iris dataset

In [7]:
gm = GaussianMixture(n_components=3)
gm.fit(df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']])

GaussianMixture(n_components=3)

In [13]:
print('Weights:\n',gm.weights_)
print('Means:\n', gm.means_)
print('Covariances:\n', gm.covariances_)
print('Converged:\m', gm.converged_)
print('Iterations:\n', gm.n_iter_)

Weights:
 [0.36539574 0.33333333 0.30127092]
Means:
 [[6.54639415 2.94946365 5.48364578 1.98726565]
 [5.006      3.418      1.464      0.244     ]
 [5.9170732  2.77804839 4.20540364 1.29848217]]
Covariances:
 [[[0.38744093 0.09223276 0.30244302 0.06087397]
  [0.09223276 0.11040914 0.08385112 0.05574334]
  [0.30244302 0.08385112 0.32589574 0.07276776]
  [0.06087397 0.05574334 0.07276776 0.08484505]]

 [[0.121765   0.098292   0.015816   0.010336  ]
  [0.098292   0.142277   0.011448   0.011208  ]
  [0.015816   0.011448   0.029505   0.005584  ]
  [0.010336   0.011208   0.005584   0.011265  ]]

 [[0.2755171  0.09662295 0.18547072 0.05478901]
  [0.09662295 0.09255152 0.09103431 0.04299899]
  [0.18547072 0.09103431 0.20235849 0.06171383]
  [0.05478901 0.04299899 0.06171383 0.03233775]]]


In [16]:
gm.predict(df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
gm.predict_proba(df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]).round(3)

array([[0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.

In [18]:
X_new, y_new = gm.sample(6)
X_new

array([[6.18710633, 2.79441805, 5.54699242, 2.21845874],
       [4.88849425, 3.04148755, 1.72266457, 0.30629637],
       [5.14411708, 3.71202676, 1.61468958, 0.33379088],
       [5.25201195, 3.49979979, 1.54029839, 0.36984572],
       [4.84598328, 3.59332669, 1.59938595, 0.29547153],
       [5.70030363, 2.91835367, 4.15039709, 1.28380132]])

In [19]:
y_new

array([0, 1, 1, 1, 1, 2])

In [20]:
gm.score_samples(df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]).round(2)

array([ 1.56,  0.79,  1.11,  0.93,  1.35, -0.1 ,  0.03,  1.63,  0.26,
        0.37,  0.85,  0.75,  0.46, -1.89, -3.44, -2.02, -1.03,  1.46,
       -0.83,  0.94, -0.75,  0.46, -3.93, -2.01, -3.11,  0.02,  0.48,
        1.4 ,  1.15,  0.71,  0.86, -0.8 , -2.41, -1.02,  0.37,  0.11,
       -1.08,  0.37,  0.09,  1.53,  0.93, -4.66, -0.43, -4.34, -2.6 ,
        0.63,  0.3 ,  1.  ,  1.15,  1.56, -2.04, -0.27, -0.85, -2.32,
       -1.16, -0.79, -0.82, -1.4 , -0.45, -1.64, -2.59, -0.6 , -2.52,
       -0.11, -1.93, -1.16, -1.27, -2.94, -5.17,  0.26, -2.49, -0.03,
       -2.19, -2.58,  0.09, -0.48, -1.33, -2.27, -0.06, -1.86,  0.13,
       -0.49,  0.53, -1.43, -2.52, -2.23, -0.32, -3.75, -0.44, -0.35,
       -1.84,  0.24,  0.7 , -1.18,  0.44, -1.74,  0.35,  0.59, -4.2 ,
        0.75, -4.19, -1.3 , -0.77, -1.39, -1.12, -2.55, -4.41, -2.35,
       -2.07, -2.53, -1.52, -0.62, -0.7 , -2.27, -3.41, -1.35, -0.8 ,
       -5.03, -7.06, -2.99, -1.04, -1.69, -3.85, -1.35, -0.95, -1.97,
       -1.41, -1.23,

In [22]:
densities = gm.score_samples(df_iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']])
density_threshold = np.percentile(densities, 2)
anomalies = df_iris[densities < density_threshold]